#version: 0.0

#os: linux 

#files:
#  - source: 
#    destination:
#  - source:
#    destination:

#permissions:
#  - object:
#    pattern:
#    except:
#    owner:
#    group:
#    mode: 
#    acls:
#     -
#    context:
#      user:
#      type:
#      range:
#    type:
      -

#hooks:
# For each deployment lifecycle event, specify multiple "location" entries 
#   if you want to run multiple scripts during that event.

#  ApplicationStop:
#    - location: 
#      timeout:
#      runas:
#    - location: 
#      timeout:
#      runas: 

#  BeforeInstall:
#    - location: 
#      timeout:
#      runas: 
#    - location: 
#      timeout:
#      runas:

#  AfterInstall:
#    - location:     
#      timeout: 
#      runas:
#    - location: 
#      timeout:
#      runas:

#  ApplicationStart:
#    - location:     
#      timeout: 
#      runas:
#    - location: 
#      timeout:
#      runas:

#  ValidateService:
#    - location:     
#      timeout: 
#      runas:
#    - location: 
#      timeout:
#      runas:
